#单机部署nacos
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    hostname: nacos
    environment:
      # 单机模式
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=suzhelan
      - NACOS_AUTH_IDENTITY_VALUE=admin
      - NACOS_AUTH_TOKEN=lTjjCQI4yokJfHIKmHuXSIJSWwIiuSHRwvVtwfZy8L8=
    ports:
      - "7848:7848"
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./data/nacos/data:/home/nacos/data
    networks:
      - nacos_net

networks:
  nacos_net:
    driver: bridge